//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS
    {
        public POS()
        {
            this.employee = new HashSet<employee>();
            this.report = new HashSet<report>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int SKK_id { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public int group_id { get; set; }
        public int chief_id { get; set; }
    
        public virtual ICollection<employee> employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual GroupOSP GroupOSP { get; set; }
        public virtual SKK SKK { get; set; }
        public virtual ICollection<report> report { get; set; }
    }
}
