//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public report()
        {
            this.report_detail = new HashSet<report_detail>();
        }
    
        public int id { get; set; }
        public int employee_id { get; set; }
        public int skk_id { get; set; }
        public int pos_id { get; set; }
        public int channel_id { get; set; }
        public decimal report_sum { get; set; }
        public System.DateTime report_date { get; set; }
        public string LNR { get; set; }
        public int report_number { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual POS POS { get; set; }
        public virtual sales_channel sales_channel { get; set; }
        public virtual SKK SKK { get; set; }
        public virtual ICollection<report_detail> report_detail { get; set; }
    }
}
