//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_channel_position
    {
        public int id { get; set; }
        public int position_id { get; set; }
        public int sales_channel_id { get; set; }
    
        public virtual position position { get; set; }
        public virtual sales_channel sales_channel { get; set; }
    }
}
