//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabel
    {
        public tabel()
        {
            this.employee = new HashSet<employee>();
        }
    
        public int id { get; set; }
        public string personnel_number { get; set; }
        public byte pn_type { get; set; }
    
        public virtual ICollection<employee> employee { get; set; }
    }
}
